-- SemanticSearch schema (template)
-- Reemplazar __PLUGIN_PREFIX__ antes de ejecutar (ej: mantis_plugin_ o mantisplugin_)

CREATE TABLE IF NOT EXISTS __PLUGIN_PREFIX__semsearch_issue (
  IssueId INT NOT NULL,
  CreatedAt INT NOT NULL DEFAULT 0,
  UpdatedAt INT NOT NULL DEFAULT 0,
  IndexedAt INT NULL DEFAULT NULL,
  Deleted TINYINT NOT NULL DEFAULT 0,
  DeletedAt INT NULL DEFAULT NULL,
  Indexable TINYINT NOT NULL DEFAULT 0,
  Hash VARCHAR(64) NOT NULL DEFAULT '',
  Empty TINYINT NOT NULL DEFAULT 0,
  Indexed TINYINT NOT NULL DEFAULT 0,
  Action VARCHAR(16) NOT NULL DEFAULT 'Nothing',
  NivelDeRevision VARCHAR(24) NOT NULL DEFAULT 'NoRevisarNada',
  PRIMARY KEY (IssueId)
);

CREATE TABLE IF NOT EXISTS __PLUGIN_PREFIX__semsearch_issuenote (
  NoteId INT NOT NULL,
  IssueId INT NOT NULL,
  CreatedAt INT NOT NULL DEFAULT 0,
  UpdatedAt INT NOT NULL DEFAULT 0,
  IndexedAt INT NULL DEFAULT NULL,
  Deleted TINYINT NOT NULL DEFAULT 0,
  DeletedAt INT NULL DEFAULT NULL,
  Indexable TINYINT NOT NULL DEFAULT 0,
  Hash VARCHAR(64) NOT NULL DEFAULT '',
  Empty TINYINT NOT NULL DEFAULT 0,
  Indexed TINYINT NOT NULL DEFAULT 0,
  Action VARCHAR(16) NOT NULL DEFAULT 'Nothing',
  NivelDeRevision VARCHAR(24) NOT NULL DEFAULT 'NoRevisarNada',
  PRIMARY KEY (NoteId, IssueId)
);

CREATE TABLE IF NOT EXISTS __PLUGIN_PREFIX__semsearch_issuenotefile (
  FileId INT NOT NULL,
  NoteId INT NOT NULL DEFAULT 0,
  IssueId INT NOT NULL,
  CreatedAt INT NOT NULL DEFAULT 0,
  UpdatedAt INT NOT NULL DEFAULT 0,
  IndexedAt INT NULL DEFAULT NULL,
  Deleted TINYINT NOT NULL DEFAULT 0,
  DeletedAt INT NULL DEFAULT NULL,
  Indexable TINYINT NOT NULL DEFAULT 0,
  Hash VARCHAR(64) NOT NULL DEFAULT '',
  Empty TINYINT NOT NULL DEFAULT 0,
  Indexed TINYINT NOT NULL DEFAULT 0,
  Action VARCHAR(16) NOT NULL DEFAULT 'Nothing',
  NivelDeRevision VARCHAR(24) NOT NULL DEFAULT 'NoRevisarNada',
  PRIMARY KEY (FileId, NoteId, IssueId)
);
